apiVersion: v1
kind: Service
metadata:
  name: java-e2e-testing-app
  labels:
    app: java-e2e-testing-app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: java-e2e-testing-app